In [1]:
import numpy as np

fpath = 'input.txt'
# fpath = 'test.txt'
# fpath = 'test2.txt'

with open(fpath, 'r') as ifp:
    height_map = [ list(map(int, list(l.strip()))) for l in ifp.readlines() ]
    height_map = np.array(height_map, dtype=int)
    
def isLocalMinimum(m, x, y):
    # Check neighbors on cardinal directions
    for offx in [-1, 0, 1]:
        for offy in [-1, 0, 1]:
            height, width = m.shape
            # Edge case: reached the edge of matrix, don't check
            if (x + offx )< 0 or (x + offx) >= width:
                continue
            if (y + offy) < 0 or (y + offy) >= height:
                continue
            
            # If on a cardinal direction, compare values
            if abs(offx) + abs(offy) == 1:
                # print(f"{x=}, {offx=}, {y=}, {offy=} | {m[y+offy, x+offx]} >= {m[y, x]}")
                if m[y+offy, x+offx] <= m[y, x]:
                    # print(f"FALSE")
                    return False
    # print("TRUE")
    return True

total = 0
check_count = 0
rows, cols = height_map.shape
for r in range(rows):
    for c in range(cols):
        check_count += 1
        x = c
        y = r
        v = height_map[y, x]
        if isLocalMinimum(height_map, x, y):
            # print(f"({r}, {c}) = {v=}")
            total += (v + 1)

print(f"{total=}")
print(f"{check_count=}")
# GUESS 1: 1632 (TOO HIGH)
# GUESS 2: 562 (CORRECT) 

total=562
check_count=10000


In [3]:
# Part 2! Basins?

import numpy as np
from functools import reduce

fpath = 'input.txt'
# fpath = 'test.txt'

with open(fpath, 'r') as ifp:
    height_map = np.genfromtxt(fpath, delimiter=1, dtype=int)

def isLocalMinimum(m, x, y):
    # Check neighbors on cardinal directions
    for offx in [-1, 0, 1]:
        for offy in [-1, 0, 1]:
            height, width = m.shape
            # Edge case: reached the edge of matrix, don't check
            if (x + offx )< 0 or (x + offx) >= width:
                continue
            if (y + offy) < 0 or (y + offy) >= height:
                continue

            # If on a cardinal direction, compare values
            if abs(offx) + abs(offy) == 1:
                # print(f"{x=}, {offx=}, {y=}, {offy=} | {m[y+offy, x+offx]} >= {m[y, x]}")
                if m[y+offy, x+offx] <= m[y, x]:
                    return False
    return True

from queue import Queue

def traverse(m, startx, starty):
    """
    Args:
        m: matrix
        x: x-coordinate
        y: y-coordinate
        v: visited coordinates
    Returns:
    """
    q = Queue()
    q.put((starty,startx))

    basin = []
    while not q.empty():
        pos = q.get()
        y, x = pos
        # print(f"Dequeue {pos=}")
        # print(f"{x=}, {y=}")

        # Marked as visited
        visited[pos] = 1
        # Add to current basin
        if pos not in basin:
            basin.append(pos)

        # Check its neighbors
        for offx in [-1, 0, 1]:
            for offy in [-1, 0, 1]:
                height, width = m.shape
                nx = x + offx
                ny = y + offy
                n = (ny, nx)
                # print(f"\tTEST: {n=}")
                
                # Case: self
                if offx == 0 and offy == 0:
                    # print(f"\t\tSELF\t{n=}")
                    continue

                # Case: out of bounds (horizontal)
                if nx < 0 or nx >= width:
                    # print(f"\t\tWIDTH violation\t{n=}")
                    continue

                # Case: out of bounds (vertical)
                if ny < 0 or ny >= height:
                    # print(f"\t\tVERTICAL violation\t{n=}")
                    continue

                if visited[n] == 1:
                    # print(f"\t\tVISITED\t{n=}")
                    continue

                # If on a cardinal direction, compare values
                if abs(offx) + abs(offy) == 1:
                    if m[n] != 9:
                        q.put(n)
                        # print(f"Enqueue {n=}")

    return basin


result = 0
rows, cols = height_map.shape
visited = np.zeros(height_map.shape)
basins = []
# Y
for r in range(rows):
    # X
    for c in range(cols):
        v = height_map[r, c]
        if isLocalMinimum(height_map, c, r):
            basins.append(traverse(height_map, c, r))

print(f"{result=}")

# visited
# height_map
# basins

basin_sizes = []

for basin in basins:
    preview = np.zeros(height_map.shape, dtype=np.uint8)
    for y, x in basin:
        preview[y,x] = 1
    print(preview)
    print(f"{len(basin)=}")
 
basin_sizes = [ len(basin) for basin in basins ]
basin_sizes = sorted(basin_sizes, reverse=True)


result = reduce((lambda a,b: a*b),basin_sizes[:3])
print(f"{result=}")

# GUESS #1: 719140356 (TOO HIGH)
# GUESS #2: 1076922 (CORRECT)


result=0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
len(basin)=14
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
len(basin)=34
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
len(basin)=26
[[1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
len(basin)=17
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
len(basin)=42
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
len(basin)=7
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
len(basin)=13
[[0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 1 0 