In [129]:
import pandas as pd
import numpy as np

# fpath = 'test.txt'
fpath = 'input.txt'
data = []
with open(fpath, 'r') as ifp:
    for line in ifp.readlines():
        data.append([ int(x) for x in list(line.strip()) ])

data = np.array(data)

height, width = data.shape
print(f"{width=}")
print(f"{height=}")

gamma_rate = np.zeros(width, dtype=np.uint8)
epsilon_rate = np.zeros(width, dtype=np.uint8)

for col in range(width):
    ones = np.count_nonzero(data[:, col])
    zeros = height - ones
    
    # Most common bit & least common bit
    if ones > zeros:
        mcb = 1
        lcb = 0
    else:
        mcb = 0
        lcb = 1
        
    # print(f"Column #{col}: {mcb=}, {lcb=} [{zeros=}, {ones=}]")
    gamma_rate[col] = mcb
    epsilon_rate[col] = lcb

print(f"{gamma_rate=}")
print(f"{epsilon_rate=}")

width=12
height=1000
gamma_rate=array([0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1], dtype=uint8)
epsilon_rate=array([1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0], dtype=uint8)


In [130]:
def arr2dec(a):
    s = ''.join(map(str, a.tolist()))
    return int(s, 2)

gamma_rate = arr2dec(gamma_rate)
epsilon_rate = arr2dec(epsilon_rate)
print(f"{gamma_rate=}*{epsilon_rate=} = {gamma_rate * epsilon_rate}")

gamma_rate=419*epsilon_rate=3676 = 1540244


In [131]:
# Part 2

# fpath = 'test.txt'
fpath = 'input.txt'
data = []
with open(fpath, 'r') as ifp:
    for line in ifp.readlines():
        data.append([ int(x) for x in list(line.strip()) ])

data = np.array(data)

height, width = data.shape
print(f"{width=}")
print(f"{height=}")


width=12
height=1000


In [132]:
data[data[:,0] == 1]

array([[1, 0, 0, ..., 0, 1, 1],
       [1, 0, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 1, 0],
       ...,
       [1, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 1, 0],
       [1, 1, 0, ..., 1, 1, 0]])

In [133]:
# For each column
def solve(mat, col=0, filter=None):
    """Given a matrix, find value"""
    if filter is None:
        return
    
    height, width = mat.shape
    
    # Base case: only one value left
    if height < 2:
        print(mat)
        return arr2dec(mat[0])
    
    ones = len(mat[mat[:, col] == 1])
    zeros = len(mat[mat[:, col] == 0])
    
    flag = None
    
    if filter == "oxygen":
        if ones == zeros:
            flag = 1
        elif ones > zeros:
            flag = 1
        else:
            flag = 0

    elif filter == "co2":
        if ones == zeros:
            flag = 0
        elif ones > zeros:
            flag = 0
        else:
            flag = 1

    else:
        return
    
    return solve(mat[mat[:, col] == flag], col+1, filter)

oxygen_generator_rating = solve(data, filter="oxygen")
co2_scrubber_rate = solve(data, filter="co2")

print(f"{oxygen_generator_rating=}")
print(f"{co2_scrubber_rate=}")
print(f"Solution: {oxygen_generator_rating * co2_scrubber_rate}")

[[0 1 0 0 1 0 0 0 1 0 0 1]]
[[1 1 1 0 0 0 1 0 0 1 0 1]]
oxygen_generator_rating=1161
co2_scrubber_rate=3621
Solution: 4203981
