In [120]:
# Part 1! Flashing dumbo octopuses!
import numpy as np

fpath = 'input.txt'
# fpath = 'test.txt'
# fpath = 'test2.txt'
# fpath = 'test3.txt'

matrix = np.genfromtxt(fpath, delimiter=1, dtype=np.uint8)

def resolve(m, state=None):
    """Resolve flashing"""
    height, width = m.shape
    if state is None:
        pts = np.argwhere(m == 10)
    else:
        pts = state
    
    # Base case: no new flashes to resolve
    if len(pts) == 0:
        return m

    flashing_pts = []
    # Otherwise, resolve flashing
    for pt in pts:
        y, x = pt
        offsets = [-1, 0, 1]
        for offy in offsets:
            for offx in offsets:
                # Skip self
                # if offx == 0 and offy == 0:
                #     continue
                
                ny = offy + y
                nx = offx + x
                # Keep in bounds
                if (ny < 0 or ny >= height) or (nx < 0 or nx >= width):
                    continue
                else:
                    m[(ny, nx)] += 1
                    if m[(ny, nx)] == 10:
                        flashing_pts.append((ny, nx))
                    
    return resolve(m, flashing_pts)

def take_a_step(m):
    # Increment energy level for all octopuses
    m += 1
    
    # Let the octopuses flash!
    m = resolve(m)

    # Reset energy levels of octopuses that flashed
    m[m>9] = 0
    flashes = np.argwhere(m == 0)

    return m, len(flashes)

def solve(m, steps=100):
    total = 0
    print(f"Before any steps:")
    print(m, end="\n\n")
    for i in range(steps):
        m, flash_counts = take_a_step(m)
        total += flash_counts
        print(f"After step {i+1}:")
        for row in m:
            print(row)
        print(f"----------------", end="\n\n")
    return total

# solve(matrix, 10)
solve(matrix, 100)

Before any steps:
[[4 8 3 6 4 8 4 5 5 5]
 [4 6 6 3 8 4 1 7 7 2]
 [3 5 1 2 4 8 4 5 5 6]
 [1 4 8 1 5 4 7 5 7 2]
 [7 7 4 1 1 8 3 4 2 2]
 [8 6 8 3 2 2 2 8 8 2]
 [4 2 1 5 2 4 4 2 3 3]
 [1 5 4 4 7 1 2 1 7 1]
 [5 7 2 5 8 5 5 7 8 6]
 [1 7 1 7 3 8 2 2 8 1]]

After step 1:
[5 9 4 7 5 9 5 6 6 6]
[5 7 7 4 9 5 2 8 8 3]
[4 6 2 3 5 9 5 6 6 7]
[2 5 9 2 6 5 8 6 8 3]
[8 8 5 2 2 9 4 5 3 3]
[9 7 9 4 3 3 3 9 9 3]
[5 3 2 6 3 5 5 3 4 4]
[2 6 5 5 8 2 3 2 8 2]
[6 8 3 6 9 6 6 8 9 7]
[2 8 2 8 4 9 3 3 9 2]
----------------

After step 2:
[7 0 6 9 8 0 7 7 7 7]
[7 9 9 6 0 9 5 9 9 4]
[6 9 5 6 8 0 8 8 7 8]
[6 0 0 5 9 9 0 8 9 4]
[0 0 0 6 4 0 8 9 6 5]
[0 0 0 7 5 5 6 0 0 5]
[8 7 5 9 5 7 7 7 8 7]
[3 7 7 9 0 7 7 7 0 6]
[7 9 6 0 0 0 0 0 0 0]
[3 9 5 0 0 0 8 8 0 6]
----------------

After step 3:
[0 6 0 0 0 5 0 0 0 0]
[0 0 0 0 7 0 0 0 0 0]
[0 0 0 0 0 7 0 0 0 0]
[9 4 6 0 0 0 7 0 0 9]
[1 1 4 0 0 8 0 0 0 8]
[3 4 6 0 0 0 0 8 5 8]
[0 0 0 0 0 0 0 0 0 9]
[9 0 0 0 6 0 0 0 4 8]
[0 0 0 4 3 3 4 3 2 1]
[7 0 9 2 1 1 9 9 1 7]
------------

1659